### ISSUE TITLE
如果你的父控件是LinearLayout 或者 FrameLayout 初始是第一个view 不能正常显示出来

### ISSUE THREAD

**Issue by RainliFu** [Rowandjj/VerticalBannerView#1]
VerticalBannerView 将你的view直接copy到demo中使用的
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">

    <saipeisi.widget.MarqueeView.VerticalBannerView
        android:id="@+id/vb_main_test"
        android:layout_width="match_parent"
        android:layout_height="400dp"/>

</RelativeLayout>
如果是这样能显示出来,但是如下代码的话不能显示出来
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">

    <saipeisi.widget.MarqueeView.VerticalBannerView
        android:id="@+id/vb_main_test"
        android:layout_width="match_parent"
        android:layout_height="400dp"/>

</LinearLayout>
在没有调用start()的时候整个firstview不能显示出来,调用start()后也是直接开始第二个view,第一个view会有部分空白;

**Comment by Rowandjj** [comment]
能否贴下代码。

我这边试了下，让父布局是FrameLayout，并没有出现你说的情况

```
 <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <com.taobao.library.VerticalBannerView
                    android:id="@+id/banner_03"
                    android:layout_width="wrap_content"
                    android:layout_height="36dp"
                    app:animDuration="900"
                    app:gap="2000"/>
            </FrameLayout>
```

**Comment by Rowandjj** [comment]
xml能否贴完整点啊。。。我连你根布局是什么都不知道:(。。。下面就比上面多了一个android:orientation="vertical"
@RainliFu

**Comment by RainliFu** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">
    <saipeisi.widget.MarqueeView.VerticalBannerView
        android:id="@+id/vb_main_test"
        android:layout_width="match_parent"
        android:layout_height="400dp"/>
</LinearLayout>

**Comment by RainliFu** [comment]
<?xml version="1.0" encoding="utf-8"?>
			<LinearLayout
				xmlns:android="http://schemas.android.com/apk/res/android"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				android:orientation="vertical"
				android:paddingBottom="@dimen/activity_vertical_margin"
				android:paddingLeft="@dimen/activity_horizontal_margin"
				android:paddingRight="@dimen/activity_horizontal_margin"
				android:paddingTop="@dimen/activity_vertical_margin">

				<saipeisi.widget.MarqueeView.VerticalBannerView
					android:id="@+id/vb_main_test"
					android:layout_width="match_parent"
					android:layout_height="400dp"/>

			</LinearLayout>
之前贴的代码前面的部分没有显示出来,不好意思
